# Generated by Django 3.2.6 on 2021-08-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('DepartamentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartamentName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=120)),
                ('Department', models.CharField(max_length=120)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=120)),
            ],
        ),
    ]
