# Generated by Django 3.2.6 on 2021-08-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departaments',
            new_name='Departments',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='DepartamentId',
            new_name='DepartmentId',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='DepartamentName',
            new_name='DepartmentName',
        ),
    ]
